// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: basic_queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertBooks = `-- name: InsertBooks :many
INSERT INTO deployments (application, version, environment, current_status, last_error_status, created_at, updated_at) VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING deployment_id, application, version, environment, current_status, last_error_status, created_at, updated_at
`

type InsertBooksParams struct {
	Application     pgtype.Text      `json:"application"`
	Version         pgtype.Text      `json:"version"`
	Environment     pgtype.Text      `json:"environment"`
	CurrentStatus   pgtype.Text      `json:"current_status"`
	LastErrorStatus pgtype.Text      `json:"last_error_status"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) InsertBooks(ctx context.Context, arg InsertBooksParams) ([]Deployment, error) {
	rows, err := q.db.Query(ctx, insertBooks,
		arg.Application,
		arg.Version,
		arg.Environment,
		arg.CurrentStatus,
		arg.LastErrorStatus,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deployment
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.DeploymentID,
			&i.Application,
			&i.Version,
			&i.Environment,
			&i.CurrentStatus,
			&i.LastErrorStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
