// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Deployment struct {
	DeploymentID    int32            `json:"deployment_id"`
	Application     pgtype.Text      `json:"application"`
	Version         pgtype.Text      `json:"version"`
	Environment     pgtype.Text      `json:"environment"`
	CurrentStatus   pgtype.Text      `json:"current_status"`
	LastErrorStatus pgtype.Text      `json:"last_error_status"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
}

type DeploymentsAudit struct {
	EventID      int32            `json:"event_id"`
	DeploymentID int32            `json:"deployment_id"`
	EventType    pgtype.Text      `json:"event_type"`
	Message      pgtype.Text      `json:"message"`
	User         pgtype.Text      `json:"user"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}
