// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Deployment struct {
	DeploymentID    int32            `json:"deployment_id"`
	Application     string           `json:"application"`
	Version         string           `json:"version"`
	Environment     string           `json:"environment"`
	CurrentStatus   string           `json:"current_status"`
	LastErrorStatus string           `json:"last_error_status"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
}

type DeploymentsAudit struct {
	EventID      int32            `json:"event_id"`
	DeploymentID int32            `json:"deployment_id"`
	EventType    string           `json:"event_type"`
	Message      string           `json:"message"`
	User         string           `json:"user"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}
